// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VodonghaPersonal.Data;

#nullable disable

namespace VodonghaPersonal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606040843_AddAISkills")]
    partial class AddAISkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VodonghaPersonal.Data.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("VodonghaPersonal.Data.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("VodonghaPersonal.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nền tảng ngân hàng trực tuyến doanh nghiệp hỗ trợ chuẩn EBICS. Quản lý hàng trăm tài khoản ngân hàng, tích hợp REST API cho ERP, multi-tenant, tự động hoá thanh toán.",
                            IsFeatured = true,
                            LiveUrl = "https://konfipay.de",
                            Order = 1,
                            Technologies = "C#,ASP.NET Core,Blazor,SQL Server,Hangfire,Azure",
                            Title = "konfipay"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Web cá nhân xây dựng với Blazor Web App .NET 10 và PostgreSQL. Deploy tự động lên Fly.io qua GitHub Actions, SCSS dark theme.",
                            GitHubUrl = "https://github.com/vodongha/vodongha-personal",
                            IsFeatured = true,
                            LiveUrl = "https://VodonghaPersonal.id.vn",
                            Order = 2,
                            Technologies = "Blazor,.NET 10,PostgreSQL,SCSS,Fly.io,Docker",
                            Title = "Personal Website"
                        });
                });

            modelBuilder.Entity("VodonghaPersonal.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Icon = "devicon-csharp-plain",
                            Name = "C# / .NET",
                            Order = 1,
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Icon = "devicon-dotnetcore-plain",
                            Name = "ASP.NET Core",
                            Order = 2,
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Icon = "devicon-rails-plain",
                            Name = "Ruby on Rails",
                            Order = 3,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Icon = "devicon-laravel-plain",
                            Name = "Laravel",
                            Order = 4,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Icon = "devicon-blazor-plain",
                            Name = "Blazor",
                            Order = 5,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Icon = "devicon-javascript-plain",
                            Name = "JavaScript",
                            Order = 6,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frontend",
                            Icon = "devicon-html5-plain",
                            Name = "HTML / CSS",
                            Order = 7,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 8,
                            Category = "Database",
                            Icon = "devicon-postgresql-plain",
                            Name = "PostgreSQL",
                            Order = 8,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 9,
                            Category = "Database",
                            Icon = "devicon-mysql-plain",
                            Name = "MySQL",
                            Order = 9,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 10,
                            Category = "Database",
                            Icon = "devicon-microsoftsqlserver-plain",
                            Name = "SQL Server",
                            Order = 10,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 11,
                            Category = "DevOps",
                            Icon = "devicon-docker-plain",
                            Name = "Docker",
                            Order = 11,
                            Proficiency = 70
                        },
                        new
                        {
                            Id = 12,
                            Category = "DevOps",
                            Icon = "devicon-git-plain",
                            Name = "Git",
                            Order = 12,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 13,
                            Category = "DevOps",
                            Icon = "devicon-azure-plain",
                            Name = "Azure",
                            Order = 13,
                            Proficiency = 65
                        },
                        new
                        {
                            Id = 14,
                            Category = "AI",
                            Icon = "devicon-python-plain",
                            Name = "Claude (Anthropic)",
                            Order = 14,
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 15,
                            Category = "AI",
                            Icon = "devicon-github-plain",
                            Name = "GitHub Copilot",
                            Order = 15,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 16,
                            Category = "AI",
                            Icon = "devicon-tensorflow-plain",
                            Name = "Prompt Engineering",
                            Order = 16,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 17,
                            Category = "AI",
                            Icon = "devicon-vscode-plain",
                            Name = "AI-Assisted Dev",
                            Order = 17,
                            Proficiency = 85
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
