// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vodongha.Data;

#nullable disable

namespace vodongha.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606042240_AddSiteSettings")]
    partial class AddSiteSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vodongha.Data.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("vodongha.Data.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("vodongha.Data.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Bachelor's degree",
                            EndYear = 2020,
                            Field = "Computer Software Engineering",
                            Order = 1,
                            School = "Nguyen Tat Thanh University",
                            StartYear = 2016
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Associate's degree",
                            EndYear = 2016,
                            Field = "Automotive Engineering Technology",
                            Order = 2,
                            School = "Vien Dong College",
                            StartYear = 2013
                        });
                });

            modelBuilder.Entity("vodongha.Data.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "cisbox GmbH",
                            Description = "Phát triển konfipay — nền tảng ngân hàng trực tuyến doanh nghiệp chuẩn EBICS. Full-stack với ASP.NET Core, Blazor WASM, SQL Server.",
                            IsCurrent = true,
                            Location = "Ho Chi Minh City",
                            Order = 1,
                            Role = "Web Developer (Onsite)",
                            StartMonth = 10,
                            StartYear = 2021
                        },
                        new
                        {
                            Id = 2,
                            Company = "BSP Software Services Corporation",
                            IsCurrent = true,
                            Location = "Ho Chi Minh City",
                            Order = 2,
                            Role = "Web Developer",
                            StartMonth = 10,
                            StartYear = 2020
                        });
                });

            modelBuilder.Entity("vodongha.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nền tảng ngân hàng trực tuyến doanh nghiệp quy mô lớn, hỗ trợ chuẩn EBICS (European Banking Standard). Quản lý hàng trăm tài khoản ngân hàng trên 13+ ngân hàng, REST API cho tích hợp ERP, multi-tenant, tự động hoá ký và nộp lệnh thanh toán. Tích hợp PayPal, Atlassian/Jira. Deploy trên Azure (SaaS) và Swisscom Docker (konfipay.ch) cho khách hàng Thụy Sĩ yêu cầu data sovereignty.",
                            IsFeatured = true,
                            LiveUrl = "https://portal.konfipay.de",
                            Order = 1,
                            Technologies = "C#,.NET 9,ASP.NET Core,Blazor WASM,SQL Server,Hangfire,Serilog,Azure,Docker,EBICS",
                            Title = "konfipay"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Web cá nhân xây dựng với Blazor Web App .NET 10 và PostgreSQL. Deploy tự động lên Fly.io qua GitHub Actions, SCSS dark theme.",
                            GitHubUrl = "https://github.com/vodongha/vodongha-personal",
                            IsFeatured = true,
                            LiveUrl = "https://vodongha.id.vn",
                            Order = 2,
                            Technologies = "Blazor,.NET 10,PostgreSQL,SCSS,Fly.io,Docker",
                            Title = "Personal Website"
                        });
                });

            modelBuilder.Entity("vodongha.Data.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Name",
                            Value = "Võ Đông Hà"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Title",
                            Value = "Full-Stack Developer"
                        },
                        new
                        {
                            Id = 3,
                            Key = "Tagline",
                            Value = "Building modern web experiences"
                        },
                        new
                        {
                            Id = 4,
                            Key = "Bio",
                            Value = "Tôi xây dựng các ứng dụng web hiện đại với .NET, Blazor và PostgreSQL. Đam mê tạo ra những sản phẩm sạch, hiệu quả và đẹp mắt."
                        },
                        new
                        {
                            Id = 5,
                            Key = "Email",
                            Value = "vodongha@hotmail.com"
                        },
                        new
                        {
                            Id = 6,
                            Key = "Phone",
                            Value = "0929758757"
                        },
                        new
                        {
                            Id = 7,
                            Key = "Location",
                            Value = "Ho Chi Minh City, Vietnam"
                        },
                        new
                        {
                            Id = 8,
                            Key = "GitHub",
                            Value = "https://github.com/vodongha"
                        },
                        new
                        {
                            Id = 9,
                            Key = "LinkedIn",
                            Value = "https://linkedin.com/in/vodongha"
                        },
                        new
                        {
                            Id = 10,
                            Key = "AvatarUrl",
                            Value = "/images/avatar.jpg"
                        });
                });

            modelBuilder.Entity("vodongha.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Icon = "devicon-csharp-plain",
                            Name = "C# / .NET",
                            Order = 1,
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Icon = "devicon-dotnetcore-plain",
                            Name = "ASP.NET Core",
                            Order = 2,
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Icon = "devicon-rails-plain",
                            Name = "Ruby on Rails",
                            Order = 3,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Icon = "devicon-laravel-plain",
                            Name = "Laravel",
                            Order = 4,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Icon = "devicon-blazor-plain",
                            Name = "Blazor",
                            Order = 5,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Icon = "devicon-javascript-plain",
                            Name = "JavaScript",
                            Order = 6,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frontend",
                            Icon = "devicon-html5-plain",
                            Name = "HTML / CSS",
                            Order = 7,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 8,
                            Category = "Database",
                            Icon = "devicon-postgresql-plain",
                            Name = "PostgreSQL",
                            Order = 8,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 9,
                            Category = "Database",
                            Icon = "devicon-mysql-plain",
                            Name = "MySQL",
                            Order = 9,
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 10,
                            Category = "Database",
                            Icon = "devicon-microsoftsqlserver-plain",
                            Name = "SQL Server",
                            Order = 10,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 11,
                            Category = "DevOps",
                            Icon = "devicon-docker-plain",
                            Name = "Docker",
                            Order = 11,
                            Proficiency = 70
                        },
                        new
                        {
                            Id = 12,
                            Category = "DevOps",
                            Icon = "devicon-git-plain",
                            Name = "Git",
                            Order = 12,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 13,
                            Category = "DevOps",
                            Icon = "devicon-azure-plain",
                            Name = "Azure",
                            Order = 13,
                            Proficiency = 65
                        },
                        new
                        {
                            Id = 14,
                            Category = "AI",
                            Icon = "devicon-python-plain",
                            Name = "Claude (Anthropic)",
                            Order = 14,
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 15,
                            Category = "AI",
                            Icon = "devicon-github-plain",
                            Name = "GitHub Copilot",
                            Order = 15,
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 16,
                            Category = "AI",
                            Icon = "devicon-tensorflow-plain",
                            Name = "Prompt Engineering",
                            Order = 16,
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 17,
                            Category = "AI",
                            Icon = "devicon-vscode-plain",
                            Name = "AI-Assisted Dev",
                            Order = 17,
                            Proficiency = 85
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
