using System.Security.Cryptography;
using System.Threading.RateLimiting;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Resend;
using VodonghaPersonal.Api;
using VodonghaPersonal.Components;
using VodonghaPersonal.Data;
using VodonghaPersonal.Hubs;
using VodonghaPersonal.Services;
using VodonghaPersonal.Shared.Models;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents()
    .AddInteractiveWebAssemblyComponents();

builder.Services.AddSignalR();

// Persist Data Protection keys to DB so they survive redeploys
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>()
    .SetApplicationName("vodongha");

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/admin/login";
        options.LogoutPath = "/admin/logout";
        options.ExpireTimeSpan = TimeSpan.FromDays(7);
        options.SlidingExpiration = true;
    });
builder.Services.AddAuthorization();
builder.Services.AddCascadingAuthenticationState();

// Use DbContextFactory for all DB access — avoids scoped/singleton DI conflicts in Blazor Server.
// The transient registration below allows health checks (and any code requiring a raw AppDbContext)
// to obtain one via the factory without registering a separate scoped AddDbContext.
builder.Services.AddDbContextFactory<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"))
           .ConfigureWarnings(w => w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning)));

builder.Services.AddTransient<AppDbContext>(sp =>
    sp.GetRequiredService<IDbContextFactory<AppDbContext>>().CreateDbContext());

builder.Services.AddHealthChecks()
    .AddDbContextCheck<AppDbContext>();

builder.Services.AddOptions();
builder.Services.AddHttpClient<ResendClient>();
builder.Services.Configure<ResendClientOptions>(o => o.ApiToken = builder.Configuration["Email:ResendApiKey"] ?? "");
builder.Services.AddTransient<IResend, ResendClient>();
builder.Services.AddScoped<EmailService>();
builder.Services.AddScoped<BlogService>();
builder.Services.AddScoped<ProjectService>();
builder.Services.AddScoped<ContactService>();
builder.Services.AddScoped<SkillService>();
builder.Services.AddScoped<ExperienceService>();
builder.Services.AddScoped<EducationService>();
builder.Services.AddScoped<LanguageService>();
builder.Services.AddScoped<SiteSettingService>();
builder.Services.AddScoped<VisitorService>();
builder.Services.AddScoped<ToastService>();
builder.Services.AddSingleton<PushNotificationService>();
builder.Services.AddHttpClient<TelegramService>()
    .AddTypedClient((http, sp) => new TelegramService(http, sp.GetRequiredService<AppSecretsService>()));
builder.Services.AddScoped<ChatService>();
builder.Services.AddScoped<TimezoneService>();
builder.Services.AddSingleton<AppSecretsService>();
builder.Services.AddSingleton<HealthMonitorService>();
builder.Services.AddScoped<CvPdfService>();
builder.Services.AddHttpClient<AiService>();
builder.Services.AddScoped<AiService>();
builder.Services.AddSingleton<CostMonitorService>();
builder.Services.AddMemoryCache();
builder.Services.AddHttpClient("deps").ConfigureHttpClient(c => c.Timeout = TimeSpan.FromSeconds(10));
builder.Services.AddSingleton<DependencyCheckService>();
builder.Services.AddHostedService(sp => sp.GetRequiredService<HealthMonitorService>());
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<AnalyticsService>();

// Rate limiter — 10 login attempts per 5 minutes per IP to prevent brute-force
builder.Services.AddRateLimiter(options =>
{
    options.AddFixedWindowLimiter("login", limiterOptions =>
    {
        limiterOptions.Window = TimeSpan.FromMinutes(5);
        limiterOptions.PermitLimit = 10;
        limiterOptions.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;
        limiterOptions.QueueLimit = 0;
    });
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
});

WebApplication app = builder.Build();

// Auto migrate on startup
using (IServiceScope scope = app.Services.CreateScope())
{
    AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.MigrateAsync();

    // Safety net for manually-written migration 20260609120000_AddPageViews.
    // Idempotent — IF NOT EXISTS / ON CONFLICT DO NOTHING. Remove once confirmed applied.
    await db.Database.ExecuteSqlRawAsync(@"
        CREATE TABLE IF NOT EXISTS ""PageViews"" (
            ""Id""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""Path""      text NOT NULL,
            ""Referrer""  text,
            ""Country""   text,
            ""CreatedAt"" timestamptz NOT NULL
        );
        CREATE INDEX IF NOT EXISTS ""IX_PageViews_CreatedAt"" ON ""PageViews"" (""CreatedAt"");
        INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
        VALUES ('20260609120000_AddPageViews', '10.0.8')
        ON CONFLICT DO NOTHING;
    ");
}

// One-time: sync secrets from ENV → DB on startup.
// Only saves keys that have a value in ENV and are NOT yet in the DB.
// After all keys are saved, this block becomes a no-op.
{
    using IServiceScope scope = app.Services.CreateScope();
    AppSecretsService secretsSvc = scope.ServiceProvider.GetRequiredService<AppSecretsService>();
    IConfiguration config = scope.ServiceProvider.GetRequiredService<IConfiguration>();

    foreach (AppSecretDefinition def in AppSecretsService.Definitions)
    {
        // Skip if already in DB
        if (await secretsSvc.HasOverrideAsync(def.Key))
        {
            continue;
        }

        string? value = config[def.Key];
        if (!string.IsNullOrWhiteSpace(value))
        {
            await secretsSvc.SaveAsync(def.Key, value);
        }
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}

app.UseStatusCodePagesWithReExecute("/not-found", createScopeForStatusCodePages: true);
app.UseHttpsRedirection();

// Redirect www → non-www canonical
app.Use(async (context, next) =>
{
    HostString host = context.Request.Host;
    if (host.Host.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
    {
        string canonical = $"https://{host.Host[4..]}{context.Request.Path}{context.Request.QueryString}";
        context.Response.Redirect(canonical, permanent: true);
        return;
    }
    await next();
});

// Track unique visitors by IP on page requests
app.Use(async (context, next) =>
{
    string path = context.Request.Path.Value ?? "";
    bool isPageRequest = context.Request.Method == "GET"
        && !path.StartsWith("/_")
        && !path.StartsWith("/health")
        && !path.StartsWith("/admin")
        && !Path.HasExtension(path);

    if (isPageRequest)
    {
        string ip = context.Request.Headers["X-Forwarded-For"].FirstOrDefault()?.Split(',')[0].Trim()
            ?? context.Connection.RemoteIpAddress?.ToString()
            ?? "unknown";
        string? ua = context.Request.Headers.UserAgent.FirstOrDefault();
        string? referrer = context.Request.Headers.Referer.FirstOrDefault();
        VisitorService visitorSvc = context.RequestServices.GetRequiredService<VisitorService>();
        AnalyticsService analyticsSvc = context.RequestServices.GetRequiredService<AnalyticsService>();
        await visitorSvc.LogAsync(ip, ua);
        _ = analyticsSvc.TrackAsync(path, referrer, ip);
    }

    await next(context);
});
app.UseRouting();
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.UseAntiforgery();
app.MapHealthChecks("/health");

app.MapPost("/admin/do-login", async (HttpContext ctx, IConfiguration config) =>
{
    string username = ctx.Request.Form["username"].ToString();
    string password = ctx.Request.Form["password"].ToString();
    string adminUser = config["Admin:Username"] ?? "admin";
    string adminPass = config["Admin:Password"] ?? "changeme";

    // Constant-time comparison to prevent timing attacks
    bool usernameMatch = CryptographicOperations.FixedTimeEquals(
        System.Text.Encoding.UTF8.GetBytes(username.PadRight(adminUser.Length)),
        System.Text.Encoding.UTF8.GetBytes(adminUser.PadRight(username.Length)));
    bool passwordMatch = CryptographicOperations.FixedTimeEquals(
        System.Text.Encoding.UTF8.GetBytes(password.PadRight(adminPass.Length)),
        System.Text.Encoding.UTF8.GetBytes(adminPass.PadRight(password.Length)));

    if (usernameMatch && passwordMatch && username.Length == adminUser.Length && password.Length == adminPass.Length)
    {
        System.Security.Claims.Claim[] claims = [new(System.Security.Claims.ClaimTypes.Name, username), new(System.Security.Claims.ClaimTypes.Role, "Admin")];
        System.Security.Claims.ClaimsIdentity identity = new(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        await ctx.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new System.Security.Claims.ClaimsPrincipal(identity));
        ctx.Response.Redirect("/admin");
    }
    else
    {
        ctx.Response.Redirect("/admin/login?error=1");

    }
}).DisableAntiforgery().RequireRateLimiting("login");

app.MapPost("/admin/logout", async (HttpContext ctx) =>
{
    await ctx.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    ctx.Response.Redirect("/");
}).RequireAuthorization();
app.MapHub<ChatHub>("/chathub");

app.MapGet("/api/cv/download", async (
    IDbContextFactory<AppDbContext> dbFactory,
    SiteSettingService settingsSvc,
    CvPdfService cvPdf,
    ILogger<Program> logger,
    IWebHostEnvironment env,
    int template = 0) =>
{
    try
    {
        Dictionary<string, string> settings = await settingsSvc.GetAllAsync();
        await using AppDbContext db = await dbFactory.CreateDbContextAsync();

        CvData data = new(
            Name: settings.GetValueOrDefault("Name", ""),
            Title: settings.GetValueOrDefault("Title", ""),
            Email: settings.GetValueOrDefault("Email", ""),
            Phone: settings.GetValueOrDefault("Phone", ""),
            Location: settings.GetValueOrDefault("Location", ""),
            GitHub: settings.GetValueOrDefault("GitHub", ""),
            LinkedIn: settings.GetValueOrDefault("LinkedIn", ""),
            Bio: settings.GetValueOrDefault("BioEn", settings.GetValueOrDefault("Bio", "")),
            AvatarUrl: settings.GetValueOrDefault("AvatarUrl", ""),
            Skills: await db.Skills.OrderBy(s => s.Order).ToListAsync(),
            Experiences: await db.Experiences.OrderBy(e => e.Order).ToListAsync(),
            Educations: await db.Educations.OrderBy(e => e.Order).ToListAsync(),
            Projects: await db.Projects.OrderBy(p => p.Order).ToListAsync()
        );

        // Pre-load avatar — read from wwwroot filesystem first (fast, reliable),
        // fall back to HTTP download for absolute URLs.
        byte[]? avatarBytes = null;
        if (!string.IsNullOrEmpty(data.AvatarUrl))
        {
            try
            {
                if (!data.AvatarUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase))
                {
                    // Relative path — read directly from wwwroot
                    string filePath = Path.Combine(env.WebRootPath, data.AvatarUrl.TrimStart('/').Replace('/', Path.DirectorySeparatorChar));
                    if (File.Exists(filePath))
                    {
                        avatarBytes = await File.ReadAllBytesAsync(filePath);
                        logger.LogInformation("CV: avatar loaded from filesystem ({Path})", filePath);
                    }
                    else
                    {
                        logger.LogWarning("CV: avatar file not found at {Path}", filePath);
                    }
                }
                else
                {
                    // Absolute URL — download via HTTP
                    using HttpClient http = new() { Timeout = TimeSpan.FromSeconds(5) };
                    avatarBytes = await http.GetByteArrayAsync(data.AvatarUrl);
                    logger.LogInformation("CV: avatar downloaded from {Url}", data.AvatarUrl);
                }
            }
            catch (Exception ex)
            {
                logger.LogWarning("CV: could not load avatar ({Url}): {Msg}", data.AvatarUrl, ex.Message);
            }
        }

        logger.LogInformation("CV download: generating PDF for {Name}, template={T}", data.Name, template);
        byte[] pdf = await Task.Run(() => cvPdf.Generate(data, template, avatarBytes));
        logger.LogInformation("CV download: PDF generated, {Bytes} bytes", pdf.Length);
        string name = data.Name.ToLower().Replace(" ", "-");
        return Results.File(pdf, "application/pdf", $"cv-{name}.pdf");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "CV download failed: {Message}", ex.Message);
        return Results.Problem($"PDF generation failed: {ex.Message}");
    }
}).RequireAuthorization();

// ── Web Push subscription endpoints ──────────────────────────────────────────

app.MapPost("/api/push/subscribe", async (HttpContext ctx, PushNotificationService pushSvc) =>
{
    var body = await ctx.Request.ReadFromJsonAsync<PushSubscribeRequest>();
    if (body is null || string.IsNullOrEmpty(body.Endpoint))
    {
        return Results.BadRequest();
    }

    // Determine IsAdmin server-side — never trust the client to set this
    bool isAdmin = ctx.User.Identity?.IsAuthenticated == true && ctx.User.IsInRole("Admin");
    await pushSvc.SaveSubscriptionAsync(body.Endpoint, body.P256DH, body.Auth, body.ChatSessionId, isAdmin);
    return Results.Ok();
}).DisableAntiforgery();

app.MapDelete("/api/push/unsubscribe", async (HttpContext ctx, PushNotificationService pushSvc) =>
{
    var body = await ctx.Request.ReadFromJsonAsync<PushUnsubscribeRequest>();
    if (body is null || string.IsNullOrEmpty(body.Endpoint))
    {
        return Results.BadRequest();
    }

    await pushSvc.RemoveSubscriptionAsync(body.Endpoint);
    return Results.Ok();
}).DisableAntiforgery();

app.MapPost("/api/telegram/webhook", async (HttpContext ctx, ChatService chatService, IConfiguration config) =>
{
    string secret = config["Telegram:WebhookSecret"] ?? "";
    string headerSecret = ctx.Request.Headers["X-Telegram-Bot-Api-Secret-Token"].FirstOrDefault() ?? "";
    if (!string.IsNullOrEmpty(secret) && headerSecret != secret)
    {
        return Results.Unauthorized();
    }

    TelegramUpdate? update = await ctx.Request.ReadFromJsonAsync<TelegramUpdate>();
    if (update != null)
    {
        await chatService.HandleTelegramWebhookAsync(update);
    }

    return Results.Ok();
}).DisableAntiforgery();

// ── One-time admin endpoint: sync all secrets from ENV → DB ──────────────────
// Call POST /api/admin/sync-secrets-to-db with Basic auth (admin credentials).
// Safe to call multiple times — skips keys with no ENV value, overwrites DB if a value exists.
app.MapPost("/api/admin/sync-secrets-to-db", async (HttpContext ctx, AppSecretsService secretsSvc, IConfiguration config) =>
{
    // Validate Basic auth
    string? authHeader = ctx.Request.Headers.Authorization.FirstOrDefault();
    if (authHeader == null || !authHeader.StartsWith("Basic ", StringComparison.Ordinal))
    {
        ctx.Response.Headers.WWWAuthenticate = "Basic realm=\"admin\"";
        return Results.Unauthorized();
    }

    string encoded = authHeader["Basic ".Length..].Trim();
    string decoded = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
    string[] parts = decoded.Split(':', 2);
    string adminUser = config["Admin:Username"] ?? "admin";
    string adminPass = config["Admin:Password"] ?? "changeme";

    if (parts.Length != 2 || parts[0] != adminUser || parts[1] != adminPass)
    {
        ctx.Response.Headers.WWWAuthenticate = "Basic realm=\"admin\"";
        return Results.Unauthorized();
    }

    List<object> results = [];

    foreach (AppSecretDefinition def in AppSecretsService.Definitions)
    {
        string? value = config[def.Key];
        if (string.IsNullOrWhiteSpace(value))
        {
            results.Add(new { key = def.Key, status = "skipped", reason = "no value in ENV/config" });
            continue;
        }

        bool ok = await secretsSvc.SaveAsync(def.Key, value);
        results.Add(new { key = def.Key, status = ok ? "saved" : "error" });
    }

    return Results.Ok(results);
}).DisableAntiforgery();

app.MapGet("/sitemap.xml", async (BlogService blogSvc, IConfiguration config) =>
{
    string baseUrl = (config["App:BaseUrl"] ?? "https://VodonghaPersonal.id.vn").TrimEnd('/');
    List<VodonghaPersonal.Shared.Models.BlogPost> posts = await blogSvc.GetAllSlugsForSitemapAsync();
    System.Text.StringBuilder sb = new();
    sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    sb.AppendLine("<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">");

    // Static pages
    foreach (string staticUrl in new[] { "", "/#projects", "/#blog", "/#contact" })
    {
        sb.AppendLine("  <url>");
        sb.AppendLine($"    <loc>{baseUrl}/{staticUrl}</loc>");
        sb.AppendLine("    <changefreq>monthly</changefreq>");
        sb.AppendLine("    <priority>0.8</priority>");
        sb.AppendLine("  </url>");
    }

    // Blog posts
    foreach (VodonghaPersonal.Shared.Models.BlogPost post in posts)
    {
        string lastmod = (post.UpdatedAt ?? post.CreatedAt).ToString("yyyy-MM-dd");
        sb.AppendLine("  <url>");
        sb.AppendLine($"    <loc>{baseUrl}/blog/{post.Slug}</loc>");
        sb.AppendLine($"    <lastmod>{lastmod}</lastmod>");
        sb.AppendLine("    <changefreq>weekly</changefreq>");
        sb.AppendLine("    <priority>0.9</priority>");
        sb.AppendLine("  </url>");
    }

    sb.AppendLine("</urlset>");
    return Results.Content(sb.ToString(), "application/xml");
});

app.MapAdminSkillsApi();
app.MapAdminProjectsApi();
app.MapAdminBlogApi();
app.MapAdminEducationApi();
app.MapAdminExperienceApi();
app.MapAdminContactsApi();
app.MapAdminSettingsApi();
app.MapAdminDashboardApi();
app.MapAdminAnalyticsApi();
app.MapAdminApiKeysApi();
app.MapAdminHealthApi();
app.MapAdminCostsApi();
app.MapAdminDependenciesApi();
app.MapAdminChatApi();
app.MapAdminMenuApi();

app.MapStaticAssets();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(VodonghaPersonal.Client._Imports).Assembly);

app.Run();

// ── DTOs ──────────────────────────────────────────────────────────────────────
// IsAdmin is intentionally removed from this DTO — it is always determined server-side from auth state.
record PushSubscribeRequest(string Endpoint, string P256DH, string Auth, int? ChatSessionId);
record PushUnsubscribeRequest(string Endpoint);
