// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VodonghaPersonal.Data;

#nullable disable

namespace VodonghaPersonal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class FixSkillIcons2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}