// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VodonghaPersonal.Data;

#nullable disable

namespace VodonghaPersonal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611120000_AddPageViewIndexes")]
    partial class AddPageViewIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
