// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VodonghaPersonal.Data;

#nullable disable

namespace VodonghaPersonal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609120000_AddPageViews")]
    partial class AddPageViews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
